# -*- coding: utf-8 -*-
"""dueno2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLko0hY_YcUZCCsuRn2xMB-ousi1ubgy
"""

dueno2=[23546987, 'Maria', 'Perez', 4789689, 'Pueyrredon  811']

for i in range(len(dueno2)):
  if i == 0:
    continue
  elif i == 2:
    continue
  else:
     print(dueno2[i])