# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xWjz3kktp8hlA7UEzPDac1fGkswI_vX
"""

Clientes= [ "Juan", "Mario", "Ariel", "Josefina", "Marianella"]
Clientes.sort()
print(Clientes)